export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const SHOW_MESSAGE = "SHOW_MESSAGE";

export const SIGNOUT = "SIGNOUT";
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const FORGET_PASSWORD = "FORGET_PASSWORD";

export const GET_ASSESSMENT = "GET_ASSESSMENT";
export const GET_ASSESSMENT_ALERTS = "GET_ASSESSMENT_ALERTS";
export const ASSESSMENT_IGNORE_SUCCESS = "ASSESSMENT_IGNORE_SUCCESS";

export const ALERTS_LIST = "ALERTS_LIST";
export const ALERTS_LIST_RULE = "ALERTS_LIST_RULE";
export const IGNORE_SUCCESS = "IGNORE_SUCCESS";

export const FILTER_OPTION = "FILTER_OPTION";

export const GET_EXP_STATS_SUCCESS = "GET_EXP_STATS_SUCCESS";

export const GET_INVENTORY_SUCCESS = "GET_INVENTORY_SUCCESS";
export const GET_CLOUD_STATS_SUCCESS = "GET_CLOUD_STATE_SUCCESS";
export const NO_DATA = "NO_DATA";

export const GET_AWS_LINK_ACCOUNT_REGIONS = "get_aws_link_account_regions";

export const accountConstants = {
    LINK_ACCOUNT_START: 'LINK_ACCOUNT_START',
    LINK_ACCOUNT_ENDS: 'LINK_ACCOUNT_ENDS',
    LINK_ACCOUNT_SUCCESS: 'LINK_ACCOUNT_SUCCESS',
    LINK_ACCOUNT_FAILURE: 'LINK_ACCOUNT_FAILURE',

    DELETE_ACCOUNT_SUCCESS: 'DELETE_ACCOUNT_SUCCESS',
    DELETE_ACCOUNT_FAILURE: 'DELETE_ACCOUNT_FAILURE',
};

export const notifConstants = {
    LINK_NOTIFS_SUCCESS: 'LINK_NOTIFS_SUCCESS',
    LINK_NOTIFS_FAILURE: 'LINK_NOTIFS_FAILURE',

    ADD_NOTIFS_SUCCESS: 'ADD_NOTIFS_SUCCESS',
    ADD_NOTIFS_FAILURE: 'ADD_NOTIFS_FAILURE',

    LINK_NOTIFS_STARTED: 'LINK_NOTIFS_STARTED',
    LINK_NOTIFS_COMPLETE: 'LINK_NOTIFS_COMPLETE',

    NOTIF_ACCLINK_SUCCESS: 'NOTIF_ACCLINK_SUCCESS',
    NOTIF_ACCLINK_FAILURE: 'NOTIF_ACCLINK_FAILURE',

    COMPLETE_ACCLINK_START: 'COMPLETE_ACCLINK_START',
    COMPLETE_ACCLINK_SUCCESS: 'COMPLETE_ACCLINK_SUCCESS',
    COMPLETE_ACCLINK_FAILURE: 'COMPLETE_ACCLINK_FAILURE',

    NOTIFS_READ_SUCCESS: 'NOTIFS_READ_SUCCESS',
};

export const assessmentConstants = {

    GET_NEW_ASSESSMENT_SUCCESS: 'GET_NEW_ASSESSMENT_SUCCESS',
    GET_NEW_ASSESSMENT_FAILURE: 'GET_NEW_ASSESSMENT_FAILURE',
};

export const authConstants = {
    UPDATE_LINK_SUCCESS: 'UPDATE_LINK_SUCCESS',
    UPDATE_LINK_FAILURE: 'UPDATE_LINK_FAILURE',
}
